baseurl = "https://www.chrisdeluca.me"
languageCode = "en-us"
title = "Chris DeLuca"
theme = "novel"
PygmentsCodeFences = true
enableRobotsTXT = true
pygmentsuseclasses = true
enableEmoji = true
menus = [ "main", "footer" ]
paginate = 20

[author]
  name = "Chris DeLuca"
  email = "contact@chrisdeluca.me"
  photo = "/images/chris-portrait.jpeg"
  region = "New York City"
  nickname = "bronzehedwick"
  pronouns = "he/him"
  identities = ["writer", "improviser", "software developer"]
  [author.key]
    id = "57B2F2C5"
    url = "/files/chris-deluca-pgp.pub.asc"

[taxonomies]
  category = "categories"
  topic = "topics"
  series = "series"
  artist = "artists"
  year = "years"

[outputFormats.MICRO]
  MediaType = "application/rss+xml"
  BaseName = "micro"
  IsHTML = false
  IsPlainText = true
  noUgly = true
  Rel = "alternate"

[outputs]
  section = ["HTML", "RSS", "JSON", "CSV", "MICRO"]

[[menu.main]]
  name = "Articles"
  url = "/article"
  weight = 50

[[menu.main]]
  name = "Projects"
  url = "/project"
  weight = 60

[[menu.main]]
  name = "Pictures"
  url = "/picture"
  weight = 65

[[menu.main]]
  name = "Quotes"
  url = "/page/quotes"
  weight = 95

[[menu.main]]
  name = "RSS"
  url = "/article/index.xml"
  weight = 100

[params]
  description = "Chris DeLuca's webbed site"

  [params.socialLinks.twitter]
    name = "ğŸ¦ Twitter"
    url = "https://twitter.com/chrisjohndeluca"
    icon = "svg/twitter.html"
    weight = 50
    featured = true

  [params.socialLinks.mastodon]
    name = "ğŸ˜ Mastodon"
    url = "https://mastodon.social/@bronzehedwick"
    weight = 40
    featured = false

  [params.socialLinks.stackoverflow]
    name = "ğŸ¥ StackOverflow"
    url = "http://stackoverflow.com/users/1143575/bronzehedwick"
    icon = "svg/stack-overflow.html"
    weight = 31
    featured = false

  [params.socialLinks.drupal]
    name = "ğŸ’§ Drupal"
    url = "https://www.drupal.org/u/bronzehedwick"
    icon = "svg/drupal.html"
    weight = 12
    featured = false

  [params.socialLinks.github]
    name = "ğŸ™ Github"
    url = "https://github.com/bronzehedwick"
    icon = "svg/github.html"
    weight = 45
    featured = true

  [params.socialLinks.pinboard]
    name = "ğŸ“Œ Pinboard"
    url = "https://pinboard.in/u:bronzehedwick"
    icon = ""
    weight = 30
    featured = false

  [params.socialLinks.newsblur]
    name = "ğŸ— Newsblur"
    url = "http://bronzehedwick.newsblur.com/"
    color = "#e6af4c"
    icon = ""
    weight = 25
    featured = false

  [params.socialLinks.keybase]
    name = "ğŸ— Keybase"
    url = "https://keybase.io/bronzehedwick"
    icon = "svg/keybase.html"
    weight = 43
    featured = true

  [params.socialLinks.youtube]
    name = "ğŸ“º YouTube"
    url = "https://www.youtube.com/channel/UChfcp3RhN0FJOnTZquDRzYw"
    icon = "svg/youtube.html"
    weight = 35
    featured = true

  [params.socialLinks.instagram]
    name = "ğŸ“· Instagram"
    url = "https://www.instagram.com/bronzehedwick/"
    icon = "svg/instagram.html"
    weight = 40
    featured = true

  [params.socialLinks.reddit]
    name = "ğŸ° Reddit"
    url = "https://www.reddit.com/user/bronzehedwick"
    color = "#0976b4"
    icon = ""
    weight = 15
    featured = false

  [params.socialLinks.linkedin]
    name = "ğŸ“‹ LinkedIn"
    url = "https://www.linkedin.com/in/christopherdeluca"
    color = "#0976b4"
    icon = ""
    weight = -50
    featured = false

  [params.socialLinks.hackernews]
    name = "ğŸ‘¾ Hacker News"
    url = "https://news.ycombinator.com/user?id=bronzehedwick"
    color = "#ff6600"
    icon = ""
    weight = 10

  [params.socialLinks.codepen]
    name = "ğŸ† CodePen"
    url = "https://codepen.io/bronzehedwick/"
    color = "#000"
    icon = ""
    weight = 8

  [params.socialLinks.devto]
    name = "ğŸ–² dev.to"
    url = "https://dev.to/bronzehedwick"
    color = "#000"
    icon = ""
    weight = 20

  [params.socialLinks.microblog]
    name = "ğŸ’¬ micro.blog"
    url = "https://micro.blog/chrisd"
    color = "#fd9526"
    icon = ""
    weight = 20

  [params.socialLinks.lobsters]
    name = "ğŸ¦ lobsters"
    url = "https://lobste.rs/u/bronzehedwick"
    color = "#0f0"
    icon = ""
    weight = 20
  [params.socialLinks.letterboxd]
    name = "ğŸ¥ Letterboxd"
    url = "https://letterboxd.com/bronzehedwick/"
    color = "#14181c"
    icon = ""
    weight = 3
  [params.socialLinks.thestorygraph]
    name = "ğŸ“š The StoryGraph"
    url = "https://app.thestorygraph.com/profile/bronzehedwick"
    color = "#3B82F6"
    icon = ""
    weight = 4
  [params.socialLinks.discogs]
    name = "ğŸ“€ Discogs"
    url = "https://www.discogs.com/user/bronzehedwick"
    color = "#111"
    icon = ""
    weight = 5

[markup.goldmark.renderer]
unsafe = true
